export type Locale = "en" | "fr" | "ar"
export const localeNames: Record<Locale, string> = { en: "English", fr: "Français", ar: "العربية" }
export const localeTags: Record<Locale, string> = { en: "en-US", fr: "fr-FR", ar: "ar-MA" }

// English keys are the source copy. Missing translations stay readable in English.
const translations: Record<"fr" | "ar", Record<string, string>> = {
  fr: {
    "Overview": "Vue d'ensemble", "Transactions": "Transactions", "Budgets": "Budgets", "Goals": "Objectifs", "Alerts": "Alertes", "Categories": "Catégories", "Settings": "Paramètres", "Sign out": "Se déconnecter", "Switch theme": "Changer le thème", "Language": "Langue",
    "Sign in": "Connexion", "Get started": "Commencer", "Create account": "Créer mon compte", "I already have an account": "J'ai déjà un compte", "View my space": "Voir mon espace", "Your finances, simplified": "Ton espace financier, simplifié", "A clearer view of your money.": "Une vue claire sur ton argent.", "Track transactions, budgets and savings goals in one place. Make better decisions every day.": "Transactions, budgets et objectifs réunis dans un espace pensé pour prendre de meilleures décisions, chaque jour.", "Free to get started · One fixed currency per account": "Gratuit pour commencer · Une devise fixe par compte", "Everything in one place": "Tout au même endroit", "Less friction. More clarity.": "Moins de friction. Plus de clarté.", "Keep a clear record of every income and expense.": "Garde une trace claire de chaque revenu et dépense.", "Set recurring limits and see where you stand.": "Fixe des limites récurrentes et vois où tu en es.", "Move toward your plans, one step at a time.": "Avance vers tes projets, étape par étape.", "Ready for a clearer view?": "Prêt à y voir plus clair ?", "Your financial space is waiting.": "Ton espace financier t'attend.", "One currency per account": "Une devise par compte", "Monthly activity": "Activité mensuelle", "Income and expenses at a glance": "Revenus et dépenses en un coup d’œil", "Savings goal": "Objectif d’épargne", "Personal project": "Projet personnel", "of the goal reached": "de l’objectif atteint", "This month": "Ce mois",
    "Welcome,": "Bonjour,", "Here's where your finances stand today.": "Voici où en sont tes finances aujourd'hui.", "Total balance": "Solde total", "Monthly income": "Revenus du mois", "Monthly expenses": "Dépenses du mois", "Tracked savings": "Épargne suivie", "Recent transactions": "Transactions récentes", "No transactions yet.": "Aucune transaction pour l'instant.", "Uncategorized": "Sans catégorie", "Monthly trend": "Évolution mensuelle", "Income and expenses over 6 months": "Revenus et dépenses sur 6 mois", "Income": "Revenus", "Expenses": "Dépenses", "By category": "Par catégorie", "This month's expenses": "Dépenses du mois", "No expenses this month.": "Aucune dépense ce mois-ci.", "Add a transaction to see your trend.": "Ajoute une transaction pour afficher ton évolution.",
    "Your income and expense history": "Historique de tes revenus et dépenses", "New transaction": "Nouvelle transaction", "Search...": "Rechercher...", "All types": "Tous les types", "All categories": "Toutes les catégories", "No transactions found.": "Aucune transaction trouvée.", "Couldn't load transactions.": "Impossible de charger les transactions.", "Expense": "Dépense", "Income item": "Revenu", "Category": "Catégorie", "Choose a category": "Choisir une catégorie", "Amount": "Montant", "Date": "Date", "Choose a date": "Choisir une date", "Description (optional)": "Description (optionnel)", "Add": "Ajouter", "Adding...": "Ajout...", "Edit transaction": "Modifier la transaction", "Delete transaction": "Supprimer la transaction", "Delete this transaction?": "Supprimer cette transaction ?", "This transaction will be permanently removed from your history.": "Cette transaction sera supprimée définitivement de ton historique.", "Deleted transaction.": "Transaction supprimée.", "Couldn't delete the transaction.": "Impossible de supprimer la transaction.", "Type": "Type", "Description": "Description", "Save": "Enregistrer", "Saving...": "Enregistrement...", "Delete": "Supprimer", "Cancel": "Annuler", "Please wait...": "Patiente...",
    "Manage spending limits by category": "Gère tes plafonds par catégorie", "New budget": "Nouveau budget", "No budgets yet. Create your first one!": "Aucun budget pour l'instant. Crée le premier !", "Weekly": "Hebdomadaire", "Monthly": "Mensuel", "Yearly": "Annuel", "Remaining": "Reste", "Over by": "Dépassement de", "Limit": "Plafond", "Recurrence": "Récurrence", "Create budget": "Créer le budget", "Creating...": "Création...", "Edit budget": "Modifier le budget", "Archive budget": "Archiver le budget", "Archive this budget?": "Archiver ce budget ?", "This budget won't be tracked in future periods.": "Ce budget ne sera plus suivi dans les périodes à venir.", "Archive": "Archiver", "Budget archived.": "Budget archivé.", "Couldn't archive the budget.": "Impossible d’archiver le budget.",
    "Savings goals": "Objectifs d'épargne", "Track your progress toward your goals": "Suis ta progression vers tes objectifs", "New goal": "Nouvel objectif", "No goals yet. Create your first one!": "Aucun objectif pour l'instant. Crée le premier !", "Couldn't load goals.": "Impossible de charger les objectifs.", "Target date:": "Échéance :", "Goal reached 🎉": "Objectif atteint 🎉", "complete": "complété", "Add funds": "Alimenter", "Add funds to": "Alimenter", "Amount to add": "Montant à ajouter", "Confirm": "Confirmer", "Goal name": "Nom de l'objectif", "Target amount": "Montant cible", "Target date (optional)": "Date cible (optionnel)", "Create goal": "Créer l'objectif", "Edit goal": "Modifier l'objectif", "Delete goal": "Supprimer l'objectif", "Delete this goal?": "Supprimer cet objectif ?", "The goal and its progress will be permanently deleted.": "L’objectif et sa progression seront supprimés définitivement.", "Goal deleted.": "Objectif supprimé.", "Couldn't delete the goal.": "Impossible de supprimer l’objectif.",
    "Stay on top of your budgets and savings goals": "Suis tes budgets et tes objectifs d’épargne", "Couldn't load alerts. Try again later.": "Impossible de charger les alertes. Réessaie plus tard.", "No alerts yet.": "Aucune alerte pour l'instant.", "Mark as read": "Marquer comme lue", "Couldn't mark the alert as read.": "Impossible de marquer l’alerte comme lue.",
    "Organize your income and expenses": "Organise tes revenus et dépenses.", "New category": "Nouvelle catégorie", "Default": "Par défaut", "Custom": "Personnalisée", "Edit category": "Modifier la catégorie", "Delete category": "Supprimer la catégorie", "Delete this category?": "Supprimer cette catégorie ?", "This category can be deleted if no transactions or budgets use it.": "Cette catégorie peut être supprimée si aucune transaction ou budget ne l’utilise.", "Category deleted.": "Catégorie supprimée.", "Couldn't delete this category.": "Impossible de supprimer cette catégorie.", "Name": "Nom", "Color": "Couleur",
    "Account": "Compte", "Manage your profile, security and appearance.": "Gère ton profil, la sécurité et l’apparence de ton espace.", "Profile": "Profil", "Your personal information": "Tes informations personnelles", "Full name": "Nom complet", "Save profile": "Enregistrer le profil", "Profile saved.": "Profil enregistré.", "Email address": "Adresse email", "Account currency": "Devise du compte", "Fixed at sign-up, with no automatic conversion.": "Fixée à l’inscription, sans conversion automatique.", "Appearance": "Apparence", "Choose the theme that works for you.": "Choisis le thème qui te convient.", "Light": "Clair", "Dark": "Sombre", "System": "Système", "Appearance updated.": "Apparence mise à jour.", "Security": "Sécurité", "Change your account password.": "Modifie le mot de passe de ton compte.", "New password": "Nouveau mot de passe", "Confirm password": "Confirmer le mot de passe", "Change password": "Modifier le mot de passe", "Changing...": "Modification...", "Password changed.": "Mot de passe modifié.", "Manage your income and expense categories.": "Organise tes catégories de revenus et dépenses.", "Manage categories": "Gérer les catégories",
    "Sign in to Rasid": "Connexion à Rasid", "Access your financial dashboard": "Accède à ton tableau de bord financier", "Email": "Email", "Password": "Mot de passe", "Signing in...": "Connexion...", "Don't have an account?": "Pas encore de compte ?", "Create an account": "Créer un compte", "Invalid email or password": "Email ou mot de passe incorrect", "Create your Rasid account": "Créer ton compte Rasid", "Start tracking your finances today": "Commence à suivre tes finances dès aujourd'hui", "Your name": "Ton nom", "Currency": "Devise", "This choice is permanent. All your data will use this currency.": "Ce choix est définitif — toutes tes données seront affichées dans cette devise.", "Already have an account?": "Déjà un compte ?", "Check your inbox to confirm your account, then sign in.": "Vérifie ta boîte mail pour confirmer ton compte, puis connecte-toi.",
  },
  ar: {
    "Overview": "نظرة عامة", "Transactions": "المعاملات", "Budgets": "الميزانيات", "Goals": "الأهداف", "Alerts": "التنبيهات", "Categories": "الفئات", "Settings": "الإعدادات", "Sign out": "تسجيل الخروج", "Switch theme": "تغيير المظهر", "Language": "اللغة",
    "Sign in": "تسجيل الدخول", "Get started": "ابدأ الآن", "Create account": "إنشاء حسابي", "I already have an account": "لدي حساب بالفعل", "View my space": "الذهاب إلى حسابي", "Your finances, simplified": "مساحتك المالية ببساطة", "A clearer view of your money.": "رؤية أوضح لأموالك.", "Track transactions, budgets and savings goals in one place. Make better decisions every day.": "تابع معاملاتك وميزانياتك وأهداف ادخارك في مكان واحد، واتخذ قرارات مالية أفضل كل يوم.", "Free to get started · One fixed currency per account": "ابدأ مجاناً · عملة ثابتة واحدة لكل حساب", "Everything in one place": "كل شيء في مكان واحد", "Less friction. More clarity.": "خطوات أقل. وضوح أكثر.", "Keep a clear record of every income and expense.": "احتفظ بسجل واضح لكل دخل ومصروف.", "Set recurring limits and see where you stand.": "حدد سقوفاً دورية واعرف أين وصلت.", "Move toward your plans, one step at a time.": "اقترب من مشاريعك خطوة بخطوة.", "Ready for a clearer view?": "هل أنت مستعد لرؤية أوضح؟", "Your financial space is waiting.": "مساحتك المالية في انتظارك.", "One currency per account": "عملة واحدة لكل حساب", "Monthly activity": "النشاط الشهري", "Income and expenses at a glance": "الدخل والمصاريف بنظرة واحدة", "Savings goal": "هدف الادخار", "Personal project": "مشروع شخصي", "of the goal reached": "من الهدف مُنجز", "This month": "هذا الشهر",
    "Welcome,": "مرحباً،", "Here's where your finances stand today.": "هذه لمحة عن وضعك المالي اليوم.", "Total balance": "الرصيد الإجمالي", "Monthly income": "دخل الشهر", "Monthly expenses": "مصاريف الشهر", "Tracked savings": "المدخرات", "Recent transactions": "آخر المعاملات", "No transactions yet.": "لا توجد معاملات بعد.", "Uncategorized": "بدون فئة", "Monthly trend": "التطور الشهري", "Income and expenses over 6 months": "الدخل والمصاريف خلال 6 أشهر", "Income": "الدخل", "Expenses": "المصاريف", "By category": "حسب الفئة", "This month's expenses": "مصاريف هذا الشهر", "No expenses this month.": "لا توجد مصاريف هذا الشهر.", "Add a transaction to see your trend.": "أضف معاملة لعرض تطورك المالي.",
    "Your income and expense history": "سجل الدخل والمصاريف", "New transaction": "معاملة جديدة", "Search...": "بحث...", "All types": "كل الأنواع", "All categories": "كل الفئات", "No transactions found.": "لم يتم العثور على معاملات.", "Couldn't load transactions.": "تعذر تحميل المعاملات.", "Expense": "مصروف", "Income item": "دخل", "Category": "الفئة", "Choose a category": "اختر فئة", "Amount": "المبلغ", "Date": "التاريخ", "Choose a date": "اختر تاريخاً", "Description (optional)": "الوصف (اختياري)", "Add": "إضافة", "Adding...": "جارٍ الإضافة...", "Edit transaction": "تعديل المعاملة", "Delete transaction": "حذف المعاملة", "Delete this transaction?": "هل تريد حذف هذه المعاملة؟", "This transaction will be permanently removed from your history.": "ستُحذف هذه المعاملة نهائياً من سجلك.", "Deleted transaction.": "تم حذف المعاملة.", "Couldn't delete the transaction.": "تعذر حذف المعاملة.", "Type": "النوع", "Description": "الوصف", "Save": "حفظ", "Saving...": "جارٍ الحفظ...", "Delete": "حذف", "Cancel": "إلغاء", "Please wait...": "يرجى الانتظار...",
    "Manage spending limits by category": "تحكم في سقف الإنفاق حسب الفئة", "New budget": "ميزانية جديدة", "No budgets yet. Create your first one!": "لا توجد ميزانيات بعد. أنشئ الأولى!", "Weekly": "أسبوعي", "Monthly": "شهري", "Yearly": "سنوي", "Remaining": "المتبقي", "Over by": "تجاوزت السقف بـ", "Limit": "السقف", "Recurrence": "التكرار", "Create budget": "إنشاء الميزانية", "Creating...": "جارٍ الإنشاء...", "Edit budget": "تعديل الميزانية", "Archive budget": "أرشفة الميزانية", "Archive this budget?": "هل تريد أرشفة هذه الميزانية؟", "This budget won't be tracked in future periods.": "لن تُتابع هذه الميزانية في الفترات القادمة.", "Archive": "أرشفة", "Budget archived.": "تمت أرشفة الميزانية.", "Couldn't archive the budget.": "تعذرت أرشفة الميزانية.",
    "Savings goals": "أهداف الادخار", "Track your progress toward your goals": "تابع تقدمك نحو أهدافك", "New goal": "هدف جديد", "No goals yet. Create your first one!": "لا توجد أهداف بعد. أنشئ الأول!", "Couldn't load goals.": "تعذر تحميل الأهداف.", "Target date:": "الموعد المستهدف:", "Goal reached 🎉": "تحقق الهدف 🎉", "complete": "مكتمل", "Add funds": "إضافة مبلغ", "Add funds to": "إضافة مبلغ إلى", "Amount to add": "المبلغ المطلوب إضافته", "Confirm": "تأكيد", "Goal name": "اسم الهدف", "Target amount": "المبلغ المستهدف", "Target date (optional)": "التاريخ المستهدف (اختياري)", "Create goal": "إنشاء الهدف", "Edit goal": "تعديل الهدف", "Delete goal": "حذف الهدف", "Delete this goal?": "هل تريد حذف هذا الهدف؟", "The goal and its progress will be permanently deleted.": "سيُحذف الهدف وتقدمه نهائياً.", "Goal deleted.": "تم حذف الهدف.", "Couldn't delete the goal.": "تعذر حذف الهدف.",
    "Stay on top of your budgets and savings goals": "تابع ميزانياتك وأهداف ادخارك", "Couldn't load alerts. Try again later.": "تعذر تحميل التنبيهات. حاول لاحقاً.", "No alerts yet.": "لا توجد تنبيهات بعد.", "Mark as read": "تحديد كمقروء", "Couldn't mark the alert as read.": "تعذر تحديد التنبيه كمقروء.",
    "Organize your income and expenses": "نظم دخلك ومصاريفك", "New category": "فئة جديدة", "Default": "افتراضية", "Custom": "مخصصة", "Edit category": "تعديل الفئة", "Delete category": "حذف الفئة", "Delete this category?": "هل تريد حذف هذه الفئة؟", "This category can be deleted if no transactions or budgets use it.": "يمكن حذف هذه الفئة إن لم ترتبط بمعاملات أو ميزانيات.", "Category deleted.": "تم حذف الفئة.", "Couldn't delete this category.": "تعذر حذف هذه الفئة.", "Name": "الاسم", "Color": "اللون",
    "Account": "الحساب", "Manage your profile, security and appearance.": "تحكم في ملفك الشخصي والأمان والمظهر.", "Profile": "الملف الشخصي", "Your personal information": "معلوماتك الشخصية", "Full name": "الاسم الكامل", "Save profile": "حفظ الملف الشخصي", "Profile saved.": "تم حفظ الملف الشخصي.", "Email address": "البريد الإلكتروني", "Account currency": "عملة الحساب", "Fixed at sign-up, with no automatic conversion.": "ثابتة منذ التسجيل، دون تحويل تلقائي.", "Appearance": "المظهر", "Choose the theme that works for you.": "اختر المظهر المناسب لك.", "Light": "فاتح", "Dark": "داكن", "System": "حسب النظام", "Appearance updated.": "تم تحديث المظهر.", "Security": "الأمان", "Change your account password.": "غيّر كلمة مرور حسابك.", "New password": "كلمة المرور الجديدة", "Confirm password": "تأكيد كلمة المرور", "Change password": "تغيير كلمة المرور", "Changing...": "جارٍ التغيير...", "Password changed.": "تم تغيير كلمة المرور.", "Manage your income and expense categories.": "نظم فئات الدخل والمصاريف.", "Manage categories": "إدارة الفئات",
    "Sign in to Rasid": "تسجيل الدخول إلى راصد", "Access your financial dashboard": "ادخل إلى لوحة التحكم المالية", "Email": "البريد الإلكتروني", "Password": "كلمة المرور", "Signing in...": "جارٍ الدخول...", "Don't have an account?": "ليس لديك حساب؟", "Create an account": "إنشاء حساب", "Invalid email or password": "بريد إلكتروني أو كلمة مرور غير صحيحة", "Create your Rasid account": "أنشئ حسابك في راصد", "Start tracking your finances today": "ابدأ بتتبع أموالك اليوم", "Your name": "اسمك", "Currency": "العملة", "This choice is permanent. All your data will use this currency.": "هذا الخيار نهائي، وستُعرض بياناتك بهذه العملة.", "Already have an account?": "لديك حساب بالفعل؟", "Check your inbox to confirm your account, then sign in.": "تحقق من بريدك لتأكيد الحساب، ثم سجل الدخول.",
  },
}
export function translate(locale: Locale, key: string): string {
  return locale === "en" ? key : translations[locale][key] ?? key
}

export function translateLegacy(locale: Locale, text: string): string {
  if (locale === "fr") return text
  const key = Object.keys(translations.fr).find((candidate) => translations.fr[candidate] === text)
  return key ? translate(locale, key) : text
}

const defaultCategories: Record<string, { en: string; ar: string }> = {
  "Salaire": { en: "Salary", ar: "الراتب" },
  "Autres revenus": { en: "Other income", ar: "دخل آخر" },
  "Alimentation": { en: "Food", ar: "الغذاء" },
  "Logement": { en: "Housing", ar: "السكن" },
  "Transport": { en: "Transport", ar: "النقل" },
  "Loisirs": { en: "Leisure", ar: "الترفيه" },
  "Santé": { en: "Health", ar: "الصحة" },
  "Abonnements": { en: "Subscriptions", ar: "الاشتراكات" },
  "Autres dépenses": { en: "Other expenses", ar: "مصاريف أخرى" },
}
export function categoryName(locale: Locale, name: string): string {
  return locale === "fr" ? name : defaultCategories[name]?.[locale] ?? name
}
export function alertMessage(locale: Locale, type: string, message: string): string {
  if (locale === "fr") return message
  if (type === "goal_reached" && message.startsWith("Objectif atteint : "))
    return `${translate(locale, "Goal reached 🎉")}: ${message.slice("Objectif atteint : ".length)}`
  const value = message.split(" : ")[1]
  if (type === "over_budget" && value)
    return locale === "ar" ? `تجاوزت الميزانية: ${value}` : `Budget exceeded: ${value}`
  if (type === "threshold_warning" && value)
    return locale === "ar" ? `وصلت إلى 80٪ من الميزانية: ${value}` : `80% budget threshold reached: ${value}`
  return message
}
Object.assign(translations.fr, {
  "Loading": "Chargement", "Loading data...": "Chargement des données...", "e.g. Groceries": "Ex : Courses", "e.g. Emergency fund": "Ex : Fonds d’urgence", "Choose your preferred language.": "Choisis ta langue préférée.", "Couldn't load categories.": "Impossible de charger les catégories.", "Couldn't load your profile.": "Impossible de charger ton profil.", "Couldn't change the theme.": "Impossible de changer le thème.", "Invalid amount": "Montant invalide", "Choose a date": "Choisir une date", "you@example.com": "toi@exemple.com", "Couldn't load the categories.": "Impossible de charger les catégories.", "Please enter a category, date and positive amount.": "Renseigne une catégorie, une date et un montant positif.",
  "Invalid email address": "Adresse email invalide", "Password must be at least 6 characters": "Le mot de passe doit contenir au moins 6 caractères", "Name must be at least 2 characters": "Le nom doit contenir au moins 2 caractères", "Select a currency": "Sélectionne une devise", "Select a category": "Sélectionne une catégorie", "Amount must be positive": "Le montant doit être positif", "Limit must be positive": "Le plafond doit être positif", "Target amount must be positive": "Le montant cible doit être positif",
})
Object.assign(translations.ar, {
  "Loading": "جارٍ التحميل", "Loading data...": "جارٍ تحميل البيانات...", "e.g. Groceries": "مثال: مشتريات", "e.g. Emergency fund": "مثال: صندوق الطوارئ", "Choose your preferred language.": "اختر لغتك المفضلة.", "Couldn't load categories.": "تعذر تحميل الفئات.", "Couldn't load your profile.": "تعذر تحميل ملفك الشخصي.", "Couldn't change the theme.": "تعذر تغيير المظهر.", "Invalid amount": "مبلغ غير صالح", "Choose a date": "اختر تاريخاً", "you@example.com": "you@example.com", "Couldn't load the categories.": "تعذر تحميل الفئات.", "Please enter a category, date and positive amount.": "أدخل فئة وتاريخاً ومبلغاً موجباً.",
  "Invalid email address": "البريد الإلكتروني غير صالح", "Password must be at least 6 characters": "يجب أن تتكون كلمة المرور من 6 أحرف على الأقل", "Name must be at least 2 characters": "يجب أن يتكون الاسم من حرفين على الأقل", "Select a currency": "اختر عملة", "Select a category": "اختر فئة", "Amount must be positive": "يجب أن يكون المبلغ موجباً", "Limit must be positive": "يجب أن يكون السقف موجباً", "Target amount must be positive": "يجب أن يكون المبلغ المستهدف موجباً",
})

Object.assign(translations.fr, {
  "Please sign in again.": "Reconnecte-toi à ton compte.", "Name is required.": "Le nom est obligatoire.", "Profile not found.": "Profil introuvable.", "Use at least 8 characters.": "Utilise au moins 8 caractères.", "Passwords do not match.": "Les mots de passe ne correspondent pas.", "Enter a name and a positive target amount.": "Saisis un nom et un montant cible positif.", "This category is used by transactions or budgets and cannot be deleted.": "Cette catégorie est utilisée par des transactions ou budgets et ne peut pas être supprimée."
})
Object.assign(translations.ar, {
  "Please sign in again.": "يرجى تسجيل الدخول مجدداً.", "Name is required.": "الاسم مطلوب.", "Profile not found.": "لم يتم العثور على الملف الشخصي.", "Use at least 8 characters.": "استخدم 8 أحرف على الأقل.", "Passwords do not match.": "كلمتا المرور غير متطابقتين.", "Enter a name and a positive target amount.": "أدخل اسماً ومبلغاً مستهدفاً موجباً.", "This category is used by transactions or budgets and cannot be deleted.": "هذه الفئة مرتبطة بمعاملات أو ميزانيات ولا يمكن حذفها."
})
